### config ###

# See https://www.mkdocs.org/user-guide/configuration/.

INHERIT: !ENV MKDOCS_BASE_CONFIG

### navigation ###

nav:
  - Home: index.md
  - Introduction: intro.md
  - Installation: installation.md
  - "Quick Start": quick-start.md
  - Reference:
      - Pages: pages.md
      - Containers: containers.md
  - View Helpers:
      - Introduction: helpers/intro.md
      - Breadcrumbs: helpers/breadcrumbs.md
      - Links: helpers/links.md
      - Menu: helpers/menu.md
      - Sitemap: helpers/sitemap.md
      - "Navigation Proxy": helpers/navigation.md
  - Cookbook:
      - "How to Create a XML Sitemap in a Mvc-Based Application?": cookbook/mvc-sitemap.md
